#!/bin/bash

sudo /usr/bin/pg_dump --host 127.0.0.1 --port 5432 --username "foi_user"  --format plain --data-only --encoding UTF8 --no-privileges --no-tablespaces --verbose --file "backup-data.sql" "foi_production"
