#!/bin/bash

/usr/bin/pg_dump --host 127.0.0.1 --port 5432 --username "postgres" --role "foi" --no-password  --format plain --data-only --encoding UTF8 --no-privileges --no-tablespaces --verbose --no-unlogged-table-data --file "backup-data.sql" "foi_production"
