#!/bin/bash

sudo /usr/bin/pg_dump --host 127.0.0.1 --port 5432 --username "foi_user"  --format plain --schema-only --no-owner --encoding UTF8 --no-privileges --no-tablespaces --verbose --file "backup-structure.sql" "foi_production"
